### ISSUE TITLE
highlight selected line

### ISSUE THREAD

**Issue by ctf0** [jacobdufault/vscode-fuzzy-search#1]
atm its kinda hard to know which line is selected from the ext list when found candidates are near to each other, so it that possible to highlight the line of the selected candidate ?

**Comment by jacobdufault** [comment]
This is part of your color theme. I use `Quiet Light` which highlights the active line.

**Comment by ctf0** [comment]
i was hoping to have a similar effect of the native search without the need to have the selected line highlight activated in the whole editor.

**Comment by jacobdufault** [comment]
Unfortunately we don't know what part of the string we're matching against, so the only real option is to highlight the entire line. If there was a custom filtering code then this would be feasible to implement.
