### ISSUE TITLE
Release v0.0.3

### ISSUE THREAD

**Issue by stevenguh** [jacobdufault/vscode-fuzzy-search#11]
Hi @jacobdufault,

Is there any chance you can release v0.0.3 which contains the addition of fuzzy search from current selection, and as well as the support for vscode remote?

I am the maintainer of VSpaceCode, which bundles your extension to provide a spacemacs like experience in VSCode. We will appreciate your update.

**Comment by jacobdufault** [comment]
Done. Thanks for the fixes!
